---
title: "Food Supply"
author: "Ivan Lysiuchenko"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Load the dataset:

```{r message=FALSE}
library(data.table)
library(reshape2)
foodBalance <- fread("materials/FoodBalanceSheets_E_All_Data.csv", encoding = "Latin-1")
```

```{r echo=FALSE}
targetElement <- unique(foodBalance[`Element Code` == 645, Element])
```

We are only interested in the element called *`r sprintf("\"%s\"", targetElement)`*. Also we need the data
on separate countries rather than regions or groups of countries.

```{r}
foodBalance <- foodBalance[`Element Code` == 645 & `Area Code` < 1000]

# How to compute 'leaders'
#itemCodes[grep("vegetables", itemCodes$Item, ignore.case = TRUE)]
#vegetableLeaders <- foodBalance[`Item Code` == 2918, .(`Area Code`, Area, Y2013)][order(-Y2013)]

foodBalance <- foodBalance[, .(`Area Code`, Area, `Item Code`, Item, Unit, Y2009, Y2010, Y2011, Y2012, Y2013)]
setnames(foodBalance, old = c("Area Code", "Area", "Item Code", "Item", "Unit"),
         new = c("areaCode", "area", "itemCode", "item", "unit"))

foodBalance <- melt(foodBalance, id.vars = c("areaCode", "area", "itemCode", "item", "unit"), 
                    measure.vars = c("Y2009", "Y2010", "Y2011", "Y2012", "Y2013"),
                    variable.name = "year", value.name = "amount")

foodBalance[, year := sapply(X = year, FUN = function(s) { regmatches(s, regexec("Y([0-9]{4})", s))[[1]][2] }, USE.NAMES = FALSE)]
```

```{r warning=FALSE, message=FALSE}
gluc <- fread("materials/NCD_GLUC_03.csv", na.strings = "No data")

# Reflect the year and sex in column names to further melt the data set
for (i in 2:ncol(gluc))
    names(gluc)[i] <- sprintf("Y%d %s", as.integer(gluc[1, ..i]), trimws(gluc[4, ..i], "both"))

# Remove unnecessary rows
gluc <- gluc[-(1:4)]

gluc <- melt(gluc, id.vars = c("V1"), measure.vars = names(gluc)[2:ncol(gluc)], 
             variable.name = "yearSex", value.name = "percentage")
setnames(gluc, old = "V1", new = "country")

gluc[, year := sapply(X = yearSex, FUN = function(s) { regmatches(s, regexec("Y([0-9]{4})", s))[[1]][2] }, USE.NAMES = FALSE)]
gluc[, sex := sapply(X = yearSex, FUN = function(s) { 
    regmatches(tolower(s), regexec("(male|female|both)", tolower(s)))[[1]][2] }, USE.NAMES = FALSE)]
gluc[, yearSex := NULL]

gluc <- dcast.data.table(gluc, country + year ~ sex, value.var = "percentage")

#strsplit(gsub("[\\]\\[\\-]", " ", gluc[1, both], perl = TRUE), "[ \t]+")[[1]]

gluc[, maleEst := as.numeric(sapply(male, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][1] }, USE.NAMES = FALSE))]
gluc[, maleMin := as.numeric(sapply(male, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][2] }, USE.NAMES = FALSE))]
gluc[, maleMax := as.numeric(sapply(male, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][3] }, USE.NAMES = FALSE))]

gluc[, femaleEst := as.numeric(sapply(female, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][1] }, USE.NAMES = FALSE))]
gluc[, femaleMin := as.numeric(sapply(female, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][2] }, USE.NAMES = FALSE))]
gluc[, femaleMax := as.numeric(sapply(female, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][3] }, USE.NAMES = FALSE))]

gluc[, bothEst := as.numeric(sapply(both, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][1] }, USE.NAMES = FALSE))]
gluc[, bothMin := as.numeric(sapply(both, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][2] }, USE.NAMES = FALSE))]
gluc[, bothMax := as.numeric(sapply(both, function(s) { strsplit(gsub("[\\]\\[\\-]", " ", s, perl = TRUE), 
                                                      "[ \t]+")[[1]][3] }, USE.NAMES = FALSE))]

gluc[, male := NULL]
gluc[, female := NULL]
gluc[, both := NULL]
```


```{r}
gluc2014 <- gluc[year == 2014 & !is.na(bothEst), .(country, bothEst, bothMin, bothMax)]
foodBalance <- foodBalance[, .(meanAmount = mean(amount)), by = .(areaCode, area, itemCode, item)]

mergedTable <- merge(foodBalance, gluc2014, by.x = "area", by.y = "country")
itemCodes <- foodBalance[, .(itemCode, item)][, .SD[1], by = .(itemCode)]
```
